require:
  - rubocop-rails

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.2.2
  Exclude:
    - '**/db/**/*'
    - '**/config/**/*'
    - '**/bin/**/*'
    - 'config.ru'
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Bundler/GemComment:
  Enabled: false
